name: Ansible Setup Verification
on:
  push:
    branches: [ main ]
jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ansible
      run: |
        sudo apt update
        sudo apt install ansible -y
    - name: Copy SSH Key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: Test Ansible Connectivity
      run: |
        ansible -i inventory.ini linux_servers -m ping
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
    - name: Run Ansible Uptime Command
      run: |
        ansible -i inventory.ini linux_servers -m command -a "uptime"
